### ISSUE TITLE
Monitor couchdb document conflicts for all instances

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-admin#4]
In some cases document sync conflicts do occur. They are resolvable through the CouchDB server UI (Fauxton) but we should have them on our monitoring radar, at least as regular as the statistics.

- admin-api: /couchdb-admin/conflicts
- into Grafana dashboard

**Comment by TheSlimvReal** [comment]
We now at least have an endpoint to get all conflicts of all DBs

**Comment by tomwwinter** [comment]
- new dashboard for couchdb created on: https://grafana.manage.aam-digital.dev/ with table for all instances and conflicts
- added oauth2 proxy for admin-api on production servers
